version: '2'
services:
    broker:
        image: "vromero/activemq-artemis:1.2.0"
    cassandra:
        image: "spotify/cassandra:latest"
    ioe-app:
        build: .
        external_links:
            - ioe-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://ioe-mysql:3306/ioe?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
        volumes:
            - ./../../../:/code
        command: ./code/gradlew -p /code
        depends_on:
          - broker
          - cassandra
    ioe-mysql:
        extends:
            file: mysql.yml
            service: ioe-mysql
